### ISSUE TITLE
AsImage

### ISSUE THREAD

**Issue by Misiu** [Fody/Resourcer#5]
Right now when we want to get embedded image from resources we must do:

    pictureBox1.Image = Image.FromStream(Resource.AsStream("Image.png"));

Can method `Resource.AsImage("Image.png")` be added? Or can this be done by extension method?

**Comment by SimonCropp** [comment]
sounds good. want to do a PR?

**Comment by Misiu** [comment]
I'm new to GitHub and not so advanced in C# but I can try :)
What file I must edit? Only `Template/Resource.cs` or are there any other places I must look/edit?

**Comment by SimonCropp** [comment]
* u need to add a placeholder here https://github.com/Fody/Resourcer/blob/master/ReferenceAssembly/Resource.cs
 * then add a new case in here https://github.com/Fody/Resourcer/blob/master/Fody/MethodProcessor.cs
 * add a new test target here https://github.com/Fody/Resourcer/blob/master/AssemblyToProcess/TargetClass.cs
 * add a new test here https://github.com/Fody/Resourcer/blob/master/Fody/ModuleWeaverTests.cs

**Comment by SimonCropp** [comment]
@Misiu any progress?

**Comment by SimonCropp** [comment]
let me know when you have time to implement this

**Comment by Misiu** [comment]
@SimonCropp I've tried adding this method, but I have problem with adding method to Template/Resource.cs
I've created method like this:

    public static Image AsImage(string path)
    {
        var stream = assembly.GetManifestResourceStream(path);
        if (stream == null)
        {
            return null;
        }
        return System.Drawing.Image.FromStream(stream);
    }

but I can't add reference to System.Drawing, can and should I include reference to that DLL? If yes then how?

I've added those lines to ReferenceFInder:

    var imageTypeDefinition = coreTypes.First(x => x.Name == "Image");
    ImageTypeReference = ModuleDefinition.ImportReference(imageTypeDefinition);

but editing HelperClassInjector is something I don't know how to do.
I've tried doing method that will mimic InjectAsStream, but no luck.
Could You help me with that?

**Comment by SimonCropp** [comment]
ok i looked into this in a little more detail and it is too much work to be justifued by the feature. the PCL subset targeted by Resourcer does not have an Image class and as such I would need to do a PCL bait and switch http://log.paulbetts.org/the-bait-and-switch-pcl-trick/ 

so closing as "wont fix"
