### ISSUE TITLE
Fody.Resourcer Error : Fody: Can only be used on string literals	

### ISSUE THREAD

**Issue by archanapereira** [Fody/Resourcer#8]
Hi,
While compiling my solution, I'm getting an error "Fody: Can only be used on string literals"
Could you please help me on this?

I have below entries in my package.config and FodyWeavers.xml file:
Package.config

```
  <package id="Fody" version="2.2.1.0" targetFramework="net462" developmentDependency="true" />
  <package id="Resourcer.Fody" version="1.6.1.0" targetFramework="net462" developmentDependency="true" />
```

FodyWeavers.xml

```
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <Resourcer/>
</Weavers>
```

**Comment by SimonCropp** [comment]
you are passing a string variable to the `Resource` helper instead of a string literal

**Comment by archanapereira** [comment]
It worked :) 
Thanks a lot Simon .

**Comment by SimonCropp** [comment]
No worries
